// Path: lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_DlJOOaScC7zoeAx8vT5vXm8TrNqQ63c',
    appId: '1:261783605700:android:60c1af8cfd7936466c5491',
    messagingSenderId: '261783605700',
    projectId: 'hare-89094',
    databaseURL: 'https://hare-89094-default-rtdb.firebaseio.com',
    storageBucket: 'hare-89094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABUEQEo3Z-Dd_TYjYmW-p6gUhQddr-yrw',
    appId: '1:261783605700:ios:d3e78e8efe20043d6c5491',
    messagingSenderId: '261783605700',
    projectId: 'hare-89094',
    databaseURL: 'https://hare-89094-default-rtdb.firebaseio.com',
    storageBucket: 'hare-89094.appspot.com',
    androidClientId: '261783605700-8igk6k6oe9jcrh9cr2fouolfk953g07q.apps.googleusercontent.com',
    iosClientId: '261783605700-ftppd0c2sglcvj4ci84gcl6l5b0ign53.apps.googleusercontent.com',
    iosBundleId: 'com.hare.store',
  );
}
